name: Bug Report2
description: File a bug report
title: "bug"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen? What were you doing just before?
      placeholder: Tell us what what happened
      value: ""
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: 1.0.0.1
    validations:
      required: true
  - type: textarea
    id: exception
    attributes:
      label: Exception message and stack
      value: ""
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
